import {
  ADMIN_TABLE_DEFAULT_PAGE_SIZE,
  ADMIN_TABLE_PAGE_SIZE_OPTIONS,
} from '@/foundation/table';

export const PRODUCT_LIST_DEFAULT_PAGE_SIZE = ADMIN_TABLE_DEFAULT_PAGE_SIZE;
export const PRODUCT_LIST_PAGE_SIZE_OPTIONS = ADMIN_TABLE_PAGE_SIZE_OPTIONS;
